
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from '../context/ThemeContext'
import Navbar from './components/Navbar';
import Footer from "./components/Footer";
import Chatbot from "./components/Navbar"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// app/layout.tsx or pages/_app.tsx (depending on your structure)

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        {/* Navbar is already fixed */}
        <Navbar />
       
        {/* Add top padding to account for fixed Navbar */}
        <main className="pt-12">
          {children}
        </main>
        <Chatbot/>
        <Footer/>
      </body>
    </html>
  );
}
